name: Go Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Tests with Coverage
      run: go test ./... -coverprofile=coverage.out

    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.out

    - name: Generate Coverage Badge (Optional)
      run: go tool cover -func=coverage.out -o coverage.txt

    - name: Display Coverage Summary
      run: |
        go tool cover -func=coverage.out
